### PR TITLE
[WIP] Colorize IRC messages in-game

### LINKED ISSUE #45: [Feature Request] Colored IRC nick-names to be displayed in-game
Currently all the text is white (non-colorized), and in-game players might not notice if they aren't already actively chatting. So, it'd be nice to see colored IRC nicks in game (just the \<name@IRC\> part); or the whole message can be fully colored too.

### PR DESCRIPTION
**Pull request by ClobberXD**
- General IRC chat will be highlighted in a blue-green hue in-game
- IRC PMs will be colored purple in-game

Closes #45

### CODE REVIEW

**Comment by sofar** [comment]
Not a bad idea. Maybe show a screenshot? I'd merge this. @kaeza?

**Comment by ClobberXD** [comment]
I'm thinking of configurable colours for these, instead of the hard-coded ones like in the commits... is it worth implementing?

**Comment by kaeza** [comment]
:+1:

**Comment by sofar** [comment]
@ClobberXD yes, totally. A simple lua table that maybe can be loaded from mod_storage would be nice.

**Comment by sofar** [comment]
`minetest.conf` settings are forced on every server on a local machine, and in the long term we'd want the IRC mod settings to be per world and not global. It's a suggestion, and not critical, though.

You can propose a colorscheme.

**Comment by ClobberXD** [comment]
Is it okay if I go with `minetest.conf` for now? This could be migrated to `mod_storage` along with the others...

**Comment by sofar** [comment]
Fine. Fine, fine

**Comment by ClobberXD** [comment]
Continued in #52. @kaeza @sofar

**Pull request closed without merging**
